### CREATE USER
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Rahmanya"
}

### GET USERS
GET http://localhost:8080/users
Accept: application/json

### GENERATE PDF
GET http://localhost:8080/users/pdf
Accept: application/pdf

### GENERATE EXCEL
GET http://localhost:8080/users/excel
Accept: application/vnd.ms-excel

### CREATE WEAVING SIZING
POST http://localhost:8080/sizing
Content-Type: application/json

{
  "bulanTahun": "Februari-2023",
  "tanggal": "1-Feb-23",
  "jenisSetKain": "NKB0369MINLAGI",
  "jenisKain": "NK14111",
  "noBenang": "NP40",
  "beamKe" : 1,
  "noBeam": "1",
  "jumlahPcsPerBeam": 1
}

### GET WEAVING SIZING
GET http://localhost:8080/sizing
Accept: application/json

### GENERATE EXCEL WEAVING SIZING
GET http://localhost:8080/sizing/excel
Accept: application/vnd.ms-excel

### GENERATE EXCEL M STOP LAPORAN KERJA USING SUBREPORT
GET http://localhost:8080/mstop/laporan-kerja/excel-subreport
Accept: application/vnd.ms-excel

### GENERATE EXCEL M STOP LAPORAN KERJA USING TABLE
GET http://localhost:8080/mstop/laporan-kerja/excel-table
Accept: application/vnd.ms-excel