### GET JOB LIST
GET {{url}}/ODataV4/Company('CRONUS New Zealand Ltd.')/Job_List?$select=No,Description,Bill_to_Customer_No,Status,Person_Responsible,Search_Description,Project_Manager
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{username}} {{password}}

### GET META DATA
GET {{url}}/ODataV4/Company('CRONUS%20New%20Zealand%20Ltd.')/powerbifinance
Accept: application/json
Authorization: Basic {{basicAuth}}

### GET META DATA SALAH
GET {{url}}/ODataV4/Company('c38f127f-a541-4bc3-93d3-b9005245c80c')/powerbifinance
Accept: application/json
Authorization: Basic {{basicAuth}}

### GET META DATA
GET {{url}}/ODataV4/Company('CRONUS%20New%20Zealand%20Ltd.')/powerbifinance
Accept: application/json
Authorization: Basic {{basicAuth}}

### GET SAMPLE LIST
GET {{url}}/ODataV4/Company('CRONUS New Zealand Ltd.')/SampleListUser
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{username}} {{password}}

### SAVE SAMPLE LIST
POST {{url}}/ODataV4/Company('CRONUS New Zealand Ltd.')/SampleListUser
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "UID": 6,
  "Email": "test_lagi@mail.com",
  "Address": "denpasar",
  "Phone": 54432,
  "Ulang_Tahun": "1990-1-1"
}