//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.25 at 05:10:05 PM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.latihan.com/java/spring/soap/jaxb", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.latihan.java.spring.soap.jaxb;
